// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmjMOR3o1tPGYC4iajDJi51AEIvrbILgA',
    appId: '1:1083088435984:android:6af0ff34f6a3a7f4e84395',
    messagingSenderId: '1083088435984',
    projectId: 'food-flag',
    storageBucket: 'food-flag.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5-CON5J8tFnQEprIRzKykCczhC2gXi_g',
    appId: '1:1083088435984:ios:8e8cfa86b1e8dad5e84395',
    messagingSenderId: '1083088435984',
    projectId: 'food-flag',
    storageBucket: 'food-flag.appspot.com',
    androidClientId: '1083088435984-78plcb8l8r6sc3lauvg01c0qtrl05asc.apps.googleusercontent.com',
    iosClientId: '1083088435984-b1d2arns474v98s6toe7dnda1uaudp7s.apps.googleusercontent.com',
    iosBundleId: 'com.foodflag.foodFlag',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu34uOexS5BDJk9j7z_GOtGtrcgwbIKdk',
    appId: '1:1083088435984:web:4d8d8c982962c2cfe84395',
    messagingSenderId: '1083088435984',
    projectId: 'food-flag',
    authDomain: 'food-flag.firebaseapp.com',
    storageBucket: 'food-flag.appspot.com',
    measurementId: 'G-W0J3FTSJHQ',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcbFazhFg9wA-SZ7y_KbIuKKcVlzqiWOg',
    appId: '1:1083088435984:web:5fbb4aa7aa12368de84395',
    messagingSenderId: '1083088435984',
    projectId: 'food-flag',
    authDomain: 'food-flag.firebaseapp.com',
    storageBucket: 'food-flag.appspot.com',
    measurementId: 'G-R5X8S3F733',
  );

}